name : This My first Next js build

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout Repository
        uses : actions/checkout@v4.2.2

      - name : Setup Node Js
        uses : actions/setup-node@v4.2.0
        with: 
          node-version: 22.x
          cache: 'npm'
      - name : Install dependencies
        run : npm install

      - name : Build Next js App
        run : npm run build

      - name: Upload build on artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: nextjs-build
          path: out/
        
        
    
